agkit:
  config:
    webPath: 'http://localhost:8083'
    fileRoot: 'D:/SDE/dev_java8/data/blog-kit/uploader/src/main/webapp/'
    pathFix: 'uploader'
    allowUrl: '*'
    #allowUrl: 'localhost:8084'
